name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 12,20,00 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: rikvik2006/badge-readme@bugfix/issue-18/badly-rendered-badges-containing-double-quotes
        with:       
          CREDLY_USER: riccardo-bussano # optional, but default will use the same from github
